### ISSUE TITLE
Field linkage rules "render failed" - unable to change, add, set field linkage rules to a form

### ISSUE THREAD

**Issue by lukaskotik** [nocobase/nocobase#7041]
## * Describe the bug

I am not able to view, edit, remove, add linkage rules for form. It happen most likely after upadete to 1.7. The form had multiple linkage rules set in Nocobase version 1.6.29. After update to 1.7.1 click on "Field linkage rules" shows normal linkage rules for very short time and then it shows "render failed":

```
  TypeError: d.includes is not a function
    at https://databaze.radiacniochrana.cz/npm.antd.1b1bd213.async.js:18:10522
    at Array.map (<anonymous>)
    at https://databaze.radiacniochrana.cz/npm.antd.1b1bd213.async.js:18:10385
    at Di (https://databaze.radiacniochrana.cz/umi.85791d12.js:54:20361)
    at Jl (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:1570)
    at wc (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:46624)
    at Rc (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:40310)
    at ef (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:40238)
    at Hu (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:40092)
    at Sl (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:36385)

```
## * Environment

- NocoBase version: 1.7.1

- Database type and version: mariadb:11
  

- OS: Debian Bookworm

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

## * How To Reproduce

Make a form with multiple linkage rules like disabling, hiding fields, setting values, etc. in older version of Nocobase, then update to the newest version of Nocobase and view field linkage rules for the form.

## Expected behavior

The settings for field likage rules should be available.

## Screenshots

![Image](https://github.com/user-attachments/assets/0a5d8a47-04f5-4619-81ca-c0c52df5e0aa)

## Logs

```
{"level":"error","message":"Diagnosis, frontend error, d.includes is not a function","stack":"TypeError: d.includes is not a function\n    at https://databaze.radiacniochrana.cz/npm.antd.1b1bd213.async.js:18:10522\n    at Array.map (<anonymous>)\n    at https://databaze.radiacniochrana.cz/npm.antd.1b1bd213.async.js:18:10385\n    at Di (https://databaze.radiacniochrana.cz/umi.85791d12.js:54:20361)\n    at Jl (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:1570)\n    at wc (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:46624)\n    at Rc (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:40310)\n    at ef (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:40238)\n    at Hu (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:40092)\n    at Sl (https://databaze.radiacniochrana.cz/umi.85791d12.js:56:36385)","meta":{},"module":"logger","submodule":"collect","method":"","app":"main","reqId":"b3434956-ee77-4160-bcc0-9a1cbbde26df","dataSourceKey":"main","timestamp":"2025-06-10 11:29:32"}
{"level":"error","message":"Diagnostic information","meta":{"location":null,"schema":{"_isJSONSchemaObject":true,"version":"2.0","type":"array","default":[{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_status_zaznamu}}","op":"$eq","rightVar":"neuplny_zaznam"}]},"actions":[{"targetFields":["nzp_data_k_doplneni"],"operator":"visible"},{"targetFields":["nzp_data_k_doplneni"],"operator":"required"},{"targetFields":["nzp_diagprim","nzp_dose","nzp_dosetype","nzp_infotext","nzp_profese","nzp_tkan","nzp_middle_name","nzp_exp_start_date","nzp_exp_end_date","nzp_pps","nzp_pps_category","nzp_stanoveni_diag","nzp_pps_status","nzp_diagdate","nzp_delka_expozice","nzp_data_source","nzp_stanovisko","nzp_algorimtus","nzp_vezen","nzp_status_diagnoza","nzp_koureni","nzp_koureni_intenzita","nzp_lokalita_dul","nzp_profese_kategorie","nzp_lekarske_profese","nzp_ostatni_profese","nzp_subject"],"operator":"notRequired"}],"title":"Neúplná data - zobrazení pole pro data k doplnění","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_status_zaznamu}}","op":"$ne","rightVar":"neuplny_zaznam"}]},"actions":[{"targetFields":["nzp_data_k_doplneni"],"operator":"none"}],"title":"Úplná data - skrytí pole pro data k doplnění","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_dosetype}}","op":"$eq","rightVar":"efektivní dávka"}]},"actions":[{"targetFields":["nzp_tkan"],"operator":"value","value":{"mode":"constant","value":"celé tělo (efektivní dávka)"}},{"targetFields":["nzp_tkan"],"operator":"disabled"}],"title":"Efektivní dávka","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_dosetype}}","op":"$eq","rightVar":"WLM"}]},"actions":[{"targetFields":["nzp_tkan"],"operator":"value","value":{"mode":"constant","value":"není relevantní"}},{"targetFields":["nzp_tkan"],"operator":"disabled"}],"title":"WLM","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_diagdate}}","op":"$dateAfter","rightVar":"2025-12-01"}]},"actions":[{"targetFields":["nzp_pps"],"operator":"notRequired"},{"targetFields":["nzp_pps_category"],"operator":"notRequired"},{"targetFields":["nzp_pps_status"],"operator":"notRequired","value":{"mode":"constant","value":"pps_nezmámé"}},{"targetFields":["nzp_algorimtus"],"operator":"value","value":{"mode":"constant","value":"vestnik 2025"}}],"title":"PPS nový věstník 2025 dále","disabled":true,"conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_pps}}","op":"$lt","rightVar":0.4},{"leftVar":"{{$nForm.nzp_pps}}","op":"$gt","rightVar":0}]},"actions":[{"targetFields":["nzp_pps_category"],"operator":"value","value":{"mode":"constant","value":"PPS_maly"}}],"title":"PPS kategorie malá","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_pps}}","op":"$gte","rightVar":0.4},{"leftVar":"{{$nForm.nzp_pps}}","op":"$lt","rightVar":0.5}]},"actions":[{"targetFields":["nzp_pps_category"],"operator":"value","value":{"mode":"constant","value":"PPS_hranicni"}}],"title":"PPS kategorie hraniční","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_pps}}","op":"$gte","rightVar":0.5}]},"actions":[{"targetFields":["nzp_pps_category"],"operator":"value","value":{"mode":"constant","value":"PPS_prevazujici"}}],"title":"PPS kategorie převažující","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_pps}}","op":"$eq","rightVar":0}]},"actions":[{"targetFields":["nzp_pps_category"],"operator":"value","value":{"mode":"constant","value":"neprokazana_prace_v_riziku"}}],"title":"PPS neprokázána práce v riziku","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_pps_status}}","op":"$eq","rightVar":"pps_vypocet"}]},"actions":[{"targetFields":["nzp_pps_category"],"operator":"disabled"}],"title":"PPS kategorie disabled pokud je PPS zadáno","conditionType":"advanced"},{"condition":{"$or":[{"leftVar":"{{$nForm.nzp_pps_status}}","op":"$in","rightVar":["pps_nezmame","pps_expertni_odhad"]}]},"actions":[{"targetFields":["nzp_pps"],"operator":"value","value":{"mode":"empty"}},{"targetFields":["nzp_pps"],"operator":"disabled"},{"targetFields":["nzp_pps_category"],"operator":"editable"},{"targetFields":["nzp_pps"],"operator":"notRequired"}],"title":"PPS nespočteno","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_algorimtus}}","op":"$eq","rightVar":"vestnik 2025"}]},"actions":[{"targetFields":["nzp_pps","nzp_pps_status"],"operator":"notRequired"}],"title":"Algoritmus 2025 - PPS","conditionType":"advanced"},{"condition":{"$or":[{"leftVar":"{{$nForm.nzp_algorimtus}}","op":"$eq","rightVar":"meze WLM a doba od 1960 "}]},"actions":[{"targetFields":["nzp_pps_status","nzp_pps"],"operator":"notRequired"},{"targetFields":["nzp_exp_start_date","nzp_exp_end_date","nzp_dosetype","nzp_dose","nzp_tkan","nzp_delka_expozice"],"operator":"notRequired"}],"title":"Algoritmus - srovnani s mezemi","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_pps_category}}","op":"$eq","rightVar":"PPS_prevazujici"}]},"actions":[{"targetFields":["nzp_stanovisko"],"operator":"value","value":{"mode":"constant","value":"splnuje podminky"}}],"title":"PPS - stanovisko","conditionType":"advanced"},{"condition":{"$or":[{"leftVar":"{{$nForm.nzp_profese_kategorie}}","op":"$empty","rightVar":true},{"leftVar":"{{$nForm.nzp_profese_kategorie}}","op":"$noneOf","rightVar":["hornik"]}]},"actions":[{"targetFields":["nzp_vezen"],"operator":"none"},{"targetFields":["nzp_lokalita_dul"],"operator":"none"}],"title":"Status vezne + lokalita - skrytý","conditionType":"advanced"},{"condition":{"$or":[{"leftVar":"{{$nForm.nzp_koureni}}","op":"$in","rightVar":["nekurak","experimentalni_kurak","nezname"]},{"leftVar":"{{$nForm.nzp_koureni}}","op":"$empty","rightVar":true}]},"actions":[{"targetFields":["nzp_koureni_intenzita"],"operator":"none"}],"title":"Intenzita koureni - skrýt","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_koureni}}","op":"$ne","rightVar":"byvaly_kurak"}]},"actions":[{"targetFields":["nzp_nekouri_od"],"operator":"none"}],"title":"byvaly kurak","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_profese_kategorie}}","op":"$noneOf","rightVar":["hornik"]}]},"actions":[{"targetFields":["nzp_profese"],"operator":"none"}],"title":"hornické profese","conditionType":"advanced"},{"condition":{"$or":[{"leftVar":"{{$nForm.nzp_profese_kategorie}}","op":"$noneOf","rightVar":["zdravotnictvi"]}]},"actions":[{"targetFields":["nzp_lekarske_profese"],"operator":"none"}],"title":"lékařské profese","conditionType":"advanced"},{"condition":{"$or":[{"leftVar":"{{$nForm.nzp_profese_kategorie}}","op":"$noneOf","rightVar":["ostatni"]}]},"actions":[{"targetFields":["nzp_ostatni_profese"],"operator":"none"}],"title":"ostatní profese","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_diagprim}}","op":"$ne","rightVar":"Zhoubné novotvary mízní a krvetvorné tkáně"}]},"actions":[{"targetFields":["nzp_krvetvorne"],"operator":"none"}],"title":"krvetvorne","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_diagprim}}","op":"$ne","rightVar":"Rakovina kůže"}]},"actions":[{"targetFields":["nzp_rakovina_kuze"],"operator":"none"}],"title":"kuze","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_diagprim}}","op":"$ne","rightVar":"Zhoubné novotvary rtu, dutiny ústní a hltanu"}]},"actions":[{"targetFields":["nzp_rty_usta_hltan"],"operator":"none"}],"title":"rty, usta, hltan","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_diagprim}}","op":"$ne","rightVar":"Zhoubné novotvary trávicího ústrojí"}]},"actions":[{"targetFields":["nzp_travici_ustroji"],"operator":"none"}],"title":"travici ustroji","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_diagprim}}","op":"$ne","rightVar":"Zhoubné novotvary močového a pohlavního ústrojí"}]},"actions":[{"targetFields":["nzp_mocove_pohlavni_ustroji"],"operator":"none"}],"title":"mocove, pohlavni ustroji","conditionType":"advanced"},{"condition":{"$and":[{"leftVar":"{{$nForm.nzp_algorimtus}}","op":"$eq","rightVar":"vestnik 2025"}]},"actions":[{"targetFields":["nzp_pps_category"],"operator":"value","value":{"mode":"constant","value":"PPS_nepocitan"}},{"targetFields":["nzp_pps_category","nzp_pps","nzp_pps_status"],"operator":"disabled"},{"targetFields":["nzp_pps"],"operator":"value","value":{"mode":"empty"}},{"targetFields":["nzp_pps_status"],"operator":"value","value":{"mode":"constant","value":"pps_nezmame"}}],"title":"Algoritmus 2025 - PPS - zaloha","disabled":true,"conditionType":"advanced"}],"x-component":"ArrayCollapse","x-decorator":"FormItem","x-component-props":{"accordion":true},"items":{"_isJSONSchemaObject":true,"version":"2.0","type":"object","x-component":"ArrayCollapse.CollapsePanel","x-component-props":{"extra":{"type":{"displayName":"EnableLinkage"},"key":null,"ref":null,"props":{},"_owner":null}},"properties":{"layout":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"FormLayout","x-component-props":{"labelStyle":{"marginTop":"6px"},"labelCol":8,"wrapperCol":16},"properties":{"conditions":{"_isJSONSchemaObject":true,"version":"2.0","x-component":"h4","x-content":"{{ t(\"Condition\") }}","name":"conditions"},"condition":{"_isJSONSchemaObject":true,"version":"2.0","x-component":"Input","x-hidden":true,"x-reactions":[{"dependencies":[".conditionType",".conditionBasic",".conditionAdvanced"],"fulfill":{"state":{"value":"{{$deps[0] === \"basic\" ? $deps[1] : $deps[2]}}"}}}],"name":"condition"},"conditionBasic":{"_isJSONSchemaObject":true,"version":"2.0","x-component":"Filter","x-visible":"{{$deps[0] === \"basic\"}}","x-component-props":{"collectionName":"nzp_cases"},"x-reactions":[{"dependencies":[".conditionType",".condition"],"fulfill":{"state":{"visible":"{{$deps[0] === \"basic\"}}","value":"{{$deps[0] === \"basic\" ? $deps[1] : undefined}}"}}}],"name":"conditionBasic"},"conditionAdvanced":{"_isJSONSchemaObject":true,"version":"2.0","x-component":"LinkageFilter","x-visible":"{{$deps[0] === \"advanced\"}}","x-component-props":{},"x-reactions":[{"dependencies":[".conditionType",".condition"],"fulfill":{"state":{"visible":"{{$deps[0] === \"advanced\"}}","value":"{{$deps[0] === \"advanced\" ? $deps[1] : undefined}}"}}}],"name":"conditionAdvanced"},"conditionType":{"_isJSONSchemaObject":true,"version":"2.0","type":"string","x-component":"Input","default":"advanced","x-hidden":true,"name":"conditionType"},"actions":{"_isJSONSchemaObject":true,"version":"2.0","x-component":"h4","x-content":"{{ t(\"Properties\") }}","name":"actions"},"action":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","name":"action"}},"name":"layout"},"remove":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"ArrayCollapse.Remove","name":"remove"},"moveUp":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"ArrayCollapse.MoveUp","name":"moveUp"},"moveDown":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"ArrayCollapse.MoveDown","name":"moveDown"},"copy":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","x-component":"ArrayCollapse.Copy","name":"copy"}}},"properties":{"add":{"_isJSONSchemaObject":true,"version":"2.0","type":"void","title":"{{ t(\"Add linkage rule\") }}","x-component":"ArrayCollapse.Addition","x-reactions":{"dependencies":["rules"],"fulfill":{"state":{}}},"name":"add"}},"name":"rules"}},"module":"logger","submodule":"collect","method":"","app":"main","reqId":"b3434956-ee77-4160-bcc0-9a1cbbde26df","dataSourceKey":"main","timestamp":"2025-06-10 11:29:32"}
{"level":"error","message":"Diagnosis, environment variables","meta":{"APP_ENV":"production","APP_PORT":"13000","API_BASE_PATH":"/api/","API_BASE_URL":"","DB_DIALECT":"mariadb","DB_UNDERSCORED":"true","DB_TIMEZONE":"+00:00","DB_LOGGING":"off"},"module":"logger","submodule":"collect","method":"","app":"main","reqId":"b3434956-ee77-4160-bcc0-9a1cbbde26df","dataSourceKey":"main","timestamp":"2025-06-10 11:29:32"}
```

**Comment by katherinehhh** [comment]
you can upgrade to 1.7.6. If there are still issues, please minimize and reproduce them in this environment: https://a_j89r6gwvkw4.v7.demo-cn.nocobase.com/admin/5ve30131jqw

**Comment by lukaskotik** [comment]
Unfortunately, upgrade did not help. Repreducing the issue could be problematic since it looks like it triggers a specific linkage rule (it is only one field linkage rule screen that cause this issue) and because of the bug I am not able to access the linkage rules I used. I will try it..

**Comment by katherinehhh** [comment]
Please minimize and reproduce in this environment https://a_f3mpqavsiht.v7.demo.nocobase.com/admin/ttae4sfeiq0


> Unfortunately, upgrade did not help. Repreducing the issue could be problematic since it looks like it triggers a specific linkage rule (it is only one field linkage rule screen that cause this issue) and because of the bug I am not able to access the linkage rules I used. I will try it..

**Comment by lukaskotik** [comment]
Reproducing the issue in provided environment would be hard because the issue started just after the update to 1.7.*. In older version (before update) it worked with no issues.

For now I can only provide additional info. According to the javascript errors shown in console, the error can be caused by CheckboxGroup component. It looks like that variable suposed to be array with checked items is not an array.

**Comment by katherinehhh** [comment]
> Reproducing the issue in provided environment would be hard because the issue started just after the update to 1.7.*. In older version (before update) it worked with no issues.
> 
> For now I can only provide additional info. According to the javascript errors shown in console, the error can be caused by CheckboxGroup component. It looks like that variable suposed to be array with checked items is not an array.

I'll investigate further on my end. Alternatively, could you provide the configuration details of the linkage rules?

**Comment by huajianzui** [comment]
我是添加规则根据状态隐藏列表中的按钮的时候就会报错,禁用不会

**Comment by katherinehhh** [comment]
> 我是添加规则根据状态隐藏列表中的按钮的时候就会报错,禁用不会

哪个版本呢，可以更新到最新版本看看

**Comment by huajianzui** [comment]
从1.7.8=>1.7.10可以啦

**Comment by katherinehhh** [comment]
We were unable to reproduce the issue in the latest version (v1.7.10). You may try upgrading to this version. If the issue cannot be reproduced on the demo we provided, please consider sharing your online environment with us.
> Reproducing the issue in provided environment would be hard because the issue started just after the update to 1.7.*. In older version (before update) it worked with no issues.
> 
> For now I can only provide additional info. According to the javascript errors shown in console, the error can be caused by CheckboxGroup component. It looks like that variable suposed to be array with checked items is not an array.
